### ISSUE TITLE
Problems with constructor

### ISSUE THREAD

**Issue by rpattcorner** [tinnou/craigslist-crawler#1]
From example:

pimpMyCraigslist]# php crawler.php 'SOMEEMAILADDRESS@gmail.com' 'http://losangeles.craigslist.org/search/apa?catAbb=apa&maxAsk=1500&sort=date#grid' '33.995039 -118.395565,34.005001 -118.420799,34.033599 -118.431957,34.037582 -118.40123,34.055362 -118.376682,34.047824 -118.359001,34.036586 -118.354366,34.020226 -118.372048,33.995039 -118.395565'
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /root/craigslist-crawler/pimpMyCraigslist/crawler.php on line 81
[root@geocloudecap pimpMyCraigslist]

**Comment by tinnou** [comment]
What version of php do you use?

2015-01-25 5:41 GMT-08:00 rpattcorner <notifications@github.com>:

**Comment by rpattcorner** [comment]
PHP 5.3.3 (cli) (built: Aug  6 2014 05:54:27)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

Also tested on mac with
PHP 5.3.28 (cli) (built: Jan 23 2014 18:02:48)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2013 Zend Technologies

Thanks!

**Comment by tinnou** [comment]
It's actually incompatible with 5.3 because the libs and I use the new
array construct "[]". Try with php > 5.4. I changed the min php version.
Thanks for the catch, I'll rewrite it at some point, the code is super ugly.

2015-01-25 10:30 GMT-08:00 rpattcorner <notifications@github.com>:

**Comment by rpattcorner** [comment]
Many thanks!

**Comment by tinnou** [comment]
Changed php min to 5.4. Closing the issue.
